name: tuto_http
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.6.0
  fl_chart: ^1.0.0
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
